const films=[
  {
    "Title": "Avatar",
    "Year": "2009",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "James Cameron",
    "Country": "USA, UK",
    "Awards": "Won 3 Oscars. Another 80 wins & 121 nominations.",
    "imdbRating": "7.9",
  },
  {
    "Title": "I Am Legend",
    "Year": "2007",
    "Genre": "Drama, Horror, Sci-Fi",
    "Director": "Francis Lawrence",
    "Country": "USA",
    "Awards": "9 wins & 21 nominations.",
    "imdbRating": "7.2",
  },
  {
    "Title": "300",
    "Year": "2006",
    "Genre": "Action, Drama, Fantasy",
    "Director": "Zack Snyder",
    "Country": "USA",
    "Awards": "16 wins & 42 nominations.",
    "imdbRating": "7.7",
  },
  {
    "Title": "The Avengers",
    "Year": "2012",
    "Genre": "Action, Sci-Fi, Thriller",
    "Director": "Joss Whedon",
    "Country": "USA",
    "Awards": "Nominated for 1 Oscar. Another 34 wins & 75 nominations.",
    "imdbRating": "8.1",
  },
  {
    "Title": "The Wolf of Wall Street",
    "Year": "2013", 
    "Genre": "Biography, Comedy, Crime",
    "Director": "Martin Scorsese",
    "Country": "USA",
    "Awards": "Nominated for 5 Oscars. Another 35 wins & 154 nominations.",
    "imdbRating": "8.2",
   
  },
  {
    "Title": "Interstellar",
    "Year": "2014", 
    "Genre": "Adventure, Drama, Sci-Fi",
    "Director": "Christopher Nolan",
    "Country": "USA, UK",
    "Awards": "Won 1 Oscar. Another 39 wins & 134 nominations.",
    "imdbRating": "8.6",
  },
  {
    "Title": "Vikings",
    "Year": "2013",
    "Genre": "Action, Drama, History",
    "Director": "N/A",
    "Country": "Ireland, Canada",
    "Awards": "Nominated for 7 Primetime Emmys. Another 17 wins & 49 nominations.",
    "imdbRating": "8.6",
  }
]
